### ISSUE TITLE
Issues with windows installation file lol.

### ISSUE THREAD

**Issue by h4rldev** [flightpkg/flight#8]
![image](https://user-images.githubusercontent.com/98224660/174471417-9638e9c5-6c31-4b5d-8ba7-28ff75a83c91.png)

**Comment by CompeyDev** [comment]
Yeah, that's because the shell installer has not been updated for v0.0.5. We recommend you use the `setup.exe`, which can be downloaded using this link: https://github.com/flightpkg/flight/releases/download/v0.0.5/setup.exe

Thanks for using flight!
